### ISSUE TITLE
‎

### ISSUE THREAD

**Issue by ghost** [MakisChristou/verifit#16]

**Comment by MakisChristou** [comment]
Hello, indeed I remember removing the code since I didn't expect anyone to use it with older versions of Android. I don't have time atm to add it back but if you make a valid PR I will merge it. The removal of that snippet is probably in some commits I did in 2023 but not sure which one.

**Comment by mkalmousli** [comment]
Thanks for the fast response! I don't know this app work, and I don't enough time too, yet I might try fixing it and making a PR in the weekend :)
