### ISSUE TITLE
thanks and question

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MakisChristou/verifit#2]
thank you for this app, hope it comes in fdroid later. now some time has passed, is there anything new?

**Comment by MakisChristou** [comment]
Glad you are enjoying the app. Are there any specific features or suggestions that you have in mind? Would be interested to hear them.

**Comment by mondlicht-und-sterne** [comment]
I will write something about it next week.

So yes, with pleasure.

**Comment by mondlicht-und-sterne** [comment]
> Glad you are enjoying the app. Are there any specific features or suggestions that you have in mind? Would be interested to hear them.

@MakisChristou A description of each exercise, i.e. the respective steps on how to perform each exercise.

**Comment by MakisChristou** [comment]
Thanks for the suggestion. Could you provide more details? How do you imagine this feature to work? For example in which screens should this be visible?

**Comment by mondlicht-und-sterne** [comment]
> In which screens should this be visible?

In the exercises

> How do you imagine this feature to work? 

At the moment the exercise is there, e.g. Chin up or Ring Dip. You might know what that is - I would first have to research what kind of exercise it is or how I should do it.

**Comment by MakisChristou** [comment]
I see. It would make sense to add another option when hold-pressing an exercise for optional info.

**Comment by mondlicht-und-sterne** [comment]
> I see. It would make sense to add another option when hold-pressing an exercise for optional info.

yes, something like that is definitely missing.

**Comment by mondlicht-und-sterne** [comment]
@MakisChristou  Is there anything new

**Comment by MakisChristou** [comment]
Hey @mondlicht-und-sterne . Thank for your interest in the app. Currently I am busy with other projects and the newest version of Android has broken the file read/write functions Verifit currently uses. So replacing them with the newest ones has higher priority than adding new features.
