### ISSUE TITLE
Importing data over rights Exercises list 

### ISSUE THREAD

**Issue by markcs** [MakisChristou/verifit#3]
When importing a backup with custom exercises, the list of exercise that are originally available in the app are removed.

ie I created two custom exercises called "Dumbbell Pull Overs" and "Dumbbell Flies" adn added them to my day.  When I exported those and then imported them again, all the existing exercises in the app are removed.

**Comment by MakisChristou** [comment]
Thanks for letting me know. I will push a fix soon.
